Traceback (most recent call last):
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geocat.datafiles as gdf
import numpy as np
from astropy.coordinates.representation import UnitSphericalRepresentation
from astropy import units

css2c_data = gdf.get('applications_files/ncl_outputs/css2c_output.txt')
css2c_data = np.loadtxt(css2c_data, delimiter=',', skiprows=6)

lat_lon = tuple(map(tuple, (css2c_data[::, 0:2])))
cart_values = css2c_data[::, 2:]
ncl_css2c = dict(zip(lat_lon, cart_values))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcoordinates[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrepresentation[39;00m [38;5;28;01mimport[39;00m UnitSphericalRepresentation
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m [38;5;28;01mimport[39;00m units
[0;32m----> 6[0m css2c_data [38;5;241m=[39m [43mgdf[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mapplications_files/ncl_outputs/css2c_output.txt[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      7[0m css2c_data [38;5;241m=[39m np[38;5;241m.[39mloadtxt(css2c_data, delimiter[38;5;241m=[39m[38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m, skiprows[38;5;241m=[39m[38;5;241m6[39m)
[1;32m      9[0m lat_lon [38;5;241m=[39m [38;5;28mtuple[39m([38;5;28mmap[39m([38;5;28mtuple[39m, (css2c_data[::, [38;5;241m0[39m:[38;5;241m2[39m])))

File [0;32m~/micromamba/envs/geocat-applications/lib/python3.12/site-packages/geocat/datafiles/__init__.py:31[0m, in [0;36mget[0;34m(fname)[0m
[1;32m     30[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(fname):
[0;32m---> 31[0m     [38;5;28;01mreturn[39;00m [43mPOOCH[49m[38;5;241;43m.[39;49m[43mfetch[49m[43m([49m[43mfname[49m[43m)[49m

File [0;32m~/micromamba/envs/geocat-applications/lib/python3.12/site-packages/pooch/core.py:561[0m, in [0;36mPooch.fetch[0;34m(self, fname, processor, downloader, progressbar)[0m
[1;32m    510[0m [38;5;28;01mdef[39;00m [38;5;21mfetch[39m([38;5;28mself[39m, fname, processor[38;5;241m=[39m[38;5;28;01mNone[39;00m, downloader[38;5;241m=[39m[38;5;28;01mNone[39;00m, progressbar[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[1;32m    511[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    512[0m [38;5;124;03m    Get the absolute path to a file in the local storage.[39;00m
[1;32m    513[0m 
[0;32m   (...)[0m
[1;32m    559[0m 
[1;32m    560[0m [38;5;124;03m    """[39;00m
[0;32m--> 561[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_assert_file_in_registry[49m[43m([49m[43mfname[49m[43m)[49m
[1;32m    563[0m     url [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_url(fname)
[1;32m    564[0m     full_path [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mabspath [38;5;241m/[39m fname

File [0;32m~/micromamba/envs/geocat-applications/lib/python3.12/site-packages/pooch/core.py:609[0m, in [0;36mPooch._assert_file_in_registry[0;34m(self, fname)[0m
[1;32m    604[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    605[0m [38;5;124;03mCheck if a file is in the registry and raise :class:`ValueError` if[39;00m
[1;32m    606[0m [38;5;124;03mit's not.[39;00m
[1;32m    607[0m [38;5;124;03m"""[39;00m
[1;32m    608[0m [38;5;28;01mif[39;00m fname [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mregistry:
[0;32m--> 609[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFile [39m[38;5;124m'[39m[38;5;132;01m{[39;00mfname[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m is not in the registry.[39m[38;5;124m"[39m)

[0;31mValueError[0m: File 'applications_files/ncl_outputs/css2c_output.txt' is not in the registry.

